apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
    - image: k8-example-api
      context: ./api
      sync:
        manual:
          - src: 'api/src/**/*'
            dest: /usr/src/k8-example-api
            strip: api
    - image: k8-example-web
      context: ./web
      sync:
        manual:
          - src: 'web/dist/**/*'
            dest: '/data/www'
            strip: web/dist
deploy:
  helm:
    releases:
      - name: skaffold-dev
        chartPath: ./app-chart
        values:
          apiImage: k8-example-api
          webImage: k8-example-web
        valuesFiles:
          - ./app-chart/values.yaml