dependencies:
  - name: postgresql
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 5.2.3
  - name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 1.6.16