apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app-chart.fullname" . }}-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "app-chart.fullname" . }}-api-pod
  template:
    metadata:
      labels:
        name: {{ template "app-chart.fullname" . }}-api-pod
    spec:
      containers:
        - name: nodejs
          image: represent-api
          imagePullPolicy: Never
          ports:
            - name: api-port
              containerPort: 80
          env:
          - name: DB_NAME
            value: {{ .Values.mariadb.db.name }}
