apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
spec:
  selector:
    name: {{ .Release.Name }}-api-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: api-port