apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: represent-app
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-web-service
            servicePort: 80
        - path: /api(/|$)(.*)
          backend:
            serviceName: {{ .Release.Name }}-api-service
            servicePort: 80