apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app-chart.fullname" . }}-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "app-chart.fullname" . }}-web-pod
  template:
    metadata:
      labels:
        name: {{ template "app-chart.fullname" . }}-web-pod
    spec:
      containers:
        - name: nginx
          image: represent-web
          imagePullPolicy: Never
          ports:
            - name: web-port
              containerPort: 80

