apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Release.Name }}-web-pod
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-web-pod
    spec:
      containers:
        - name: nginx
          image: {{ .Values.webImage }}
          imagePullPolicy: Never
          ports:
            - name: web-port
              containerPort: 80

