apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    name: api-service
spec:
  selector:
    name: api-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: api-port
  type: LoadBalancer
